# sudo permissions rfequired
sudo: required
language: generic 
services:
  - dockerfile

before_install:
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin; 
  - docker build -t annestani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true annestani/docker-react npm run test 

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-1-374915934591"
  bucket_path: "docker-react"
  on: 
    branch: master



