# sudo permissions rfequired
sudo: required
language: generic 
services:
  - dockerfile

before_install:
  - echo “$DOCKER_PASSWORD” | docker login -u “$DOCKER_USERNAME” password-stdin && docker build -t annestani/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true annestani/docker-react npm run test





